theme: jekyll-theme-minimal
include: [".well-known"]
title: Nikola Tesla GPT
description: The home of the original Nikola custom GPT! You can use Nikola to help manage your Tesla fleet! Starting with vehicles and expanding to manage solar soon!
